### ISSUE TITLE
Pryzm Health and NCR Concept Recognisers blocked by CORS policy

### ISSUE THREAD

**Issue by azankl** [azankl/Ontoclick#1]
When I try to use the Pryzm Health or the NCR Concept Recognisers on some highlighted text, no results appear and I found the error messages below in the Chrome Extensions Window:

> Access to XMLHttpRequest at 'https://knowledge.pryzm.health/api/cr/v1/annotate?apiKey=3156e102-4add-4098-926f-74fb1e49d38c' from origin 'chrome-extension://dkknhicdbaklmnblmmliepfeekmojahf' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> 
> Access to XMLHttpRequest at 'https://ncr.ccm.sickkids.ca/curr/match/?text=optic+disc+swelling+m' from origin 'chrome-extension://dkknhicdbaklmnblmmliepfeekmojahf' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Can this be easily fixed, maybe by adding the 'Access-Control-Allow-Origin' header mentioned in the error message?
If it cannot be easily fixed, we can simply remove the Pryzm Health and NCR Concept Recognisers from Ontoclick.

**Comment by anthonyaxu** [comment]
I have been able to create a workaround that allows OntoClick to access the servers in question. I wasn't sure how to add the edits onto this repo but I have added the changes onto the original repo.

**Comment by azankl** [comment]
Thanks! Since its only 2 lines, I just replicated the change here and it works! Now I just need to submit it to the Chrome Store again, haha. v1.0.1
