### ISSUE TITLE
DevTools failed to load source map Error

### ISSUE THREAD

**Issue by azankl** [azankl/Ontoclick#18]
When I try to look up a highlighted term with Ontoclick, the Results pane shows 'loading' but never returns a result. When I examine the console log, I see the error messages below. Tried this on my desktop and laptop (both macOS 11.5.1, Chrome 94.0.4606.54).

```
DevTools failed to load source map: Could not load content for chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/client/build/scripts/sentry.bundle.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/client/build/scripts/katex.bundle.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/client/build/scripts/showdown.bundle.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

**Comment by azankl** [comment]
Working now, might have been the stupid hospital firewall playing tricks on me.

**Comment by sepetab** [comment]
Hi Andreas,

I had the issue as well and we were trying to debug. Worked for me after updating Chrome.

I would say something funny happened. This will also happen if the same key is being used simultaneously by a lot of people, not issue in this case.

Anthony said he will take a look at it to keep things up to date.

Great that it works now.

Regards,
Aravind

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
